### PR TITLE
Refs #NAVIO-725 - Fix email format for registration form

### PR DESCRIPTION
**Pull request by Netmisa**
# Description

This PR Fix email format encode when we create user.

### CODE REVIEW

**Review by pbougue — COMMENTED** [review]
Not sure : don't we also want to do that on some other things?

**Review by datanel — COMMENTED** [review]
urlencode is not recommanded for emails

see http://php.net/manual/fr/function.urlencode.php#91855

**Comment by Netmisa** [comment]
I'm not sure about this patch, I think we need to discuss about it.

**Comment by pbougue** [comment]
OK, so there are 2 patches to be done for that problem, and behavior seems to differ on some platforms at least on one of the 2 patches.

**Pull request closed without merging**
